### ISSUE TITLE
Generic methods not used property access

### ISSUE THREAD

**Issue by dmachehin** [c9s/LazyRecord#115]
Column schema strict var type (instead string), inflator work only if access to property.
Generic methods getId(), getName(),... not used access to property, it get data from source $this->_data...

Example:
In Schema column i'm write ```$this->column('geo')->text()
        ->inflator(function($value) {
        	return array_map('intval', explode(',', $value));
        })
        ->deflator(function($value) {
        	return join(',', $value);
        });```
Then output results
```$project->geo``` return ```array(123,456,678)```
```$project->getGeo()``` return ```123,456,678```

**Comment by c9s** [comment]
Shall be fixed in e270250f43ead695e8789ec6437c4cca544ec9dd , can you give it a try?

**Comment by dmachehin** [comment]
All works fine.
