### ISSUE TITLE
LazyRecord\Schema\ColumnDeclare::required() - not work

### ISSUE THREAD

**Issue by dmachehin** [c9s/LazyRecord#116]
LazyRecord\Schema\ColumnDeclare method required() wrong set notNull value.

Original: ```/**
     * This method is an alias of "notNull"
     */
    public function required()
    {
        $this->notNull = false;
        return $this;
    }```

For fix:```
$this->notNull = true;
```

**Comment by dmachehin** [comment]
"notNull" don't writes to attributes (not exists in proxy class)

Creating proxy classes used export method, in this method not use notNull manual get property.

**Comment by c9s** [comment]
@dmachehin Fixed on master branch.

**Comment by c9s** [comment]
@dmachehin  does it work you now?

**Comment by c9s** [comment]
`required()` now enables `notNull` but provide software validation.
