### ISSUE TITLE
create/update->result->validations: different validate output

### ISSUE THREAD

**Issue by dmachehin** [c9s/LazyRecord#120]
Different object result->validations output type

If call create method, i'm receive array[stdObject]: ```object(stdClass)#49 (3) {
  ["valid"]=>
  bool(false)
  ["message"]=>
  string(18) "Validation failed."
  ["field"]=>
  string(10) "first_name"
}```

If call update method, receive array[array]: ```array(3) {
  ["valid"]=>
  bool(false)
  ["message"]=>
  string(18) "Validation failed."
  ["field"]=>
  string(10) "first_name"
}```

**Comment by c9s** [comment]
Yeah that should be fixed.

**Comment by c9s** [comment]
Fixed in 03dab71

**Comment by c9s** [comment]
I've applied the patch on 2.2 branch.

**Comment by c9s** [comment]
It should return stdObject now.

**Comment by c9s** [comment]
fixed
